import type { Pattern } from './patterns.js'
import type { GeneratedFile } from '../types.js'

/**
 * Generate Claude Code skills from extracted conversation patterns.
 */
export function generateSkillsFromPatterns(patterns: Pattern[], _cwd: string): GeneratedFile[] {
  const files: GeneratedFile[] = []

  for (const pattern of patterns) {
    const slug = pattern.name.replace(/[^a-z0-9-]/g, '-').replace(/-+/g, '-')
    const skillName = `learned-${slug}`

    const stepsSection = pattern.steps.map((s, i) => `${i + 1}. ${s}`).join('\n')
    const examplesSection = pattern.examplePrompts.length > 0
      ? `\n## Example Prompts\n\n${pattern.examplePrompts.map(p => `- "${p}"`).join('\n')}\n`
      : ''
    const fileSection = pattern.filePatterns.length > 0
      ? `\n## Related Files\n\n${pattern.filePatterns.map(f => `- \`${f}\``).join('\n')}\n`
      : ''

    const content = `---
name: ${skillName}
description: ${pattern.description} (auto-generated from conversation history)
allowed-tools: Read, Glob, Grep, Write, Edit, Bash
---

# ${pattern.name.replace(/-/g, ' ').replace(/\b\w/g, c => c.toUpperCase())}

> Auto-generated from ${pattern.frequency} conversation sessions.
> Customize this skill to match your exact workflow.

## Steps

${stepsSection}
${examplesSection}${fileSection}
## Notes

This skill was generated by \`claude-harness learn\` from your conversation history.
Edit it freely — it won't be overwritten unless you run \`learn\` with \`--force\`.
`

    files.push({
      path: `.claude/skills/${skillName}/SKILL.md`,
      content,
      preserveExisting: true,
    })
  }

  return files
}
