#!/usr/bin/env bash
# WorktreeCreate hook handler
# Called by Claude Code when a worktree is created.
# Sets up application-level isolation: unique ports, .env, database, docker stack.
# MUST output the worktree path as the last line to stdout.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
source "$SCRIPT_DIR/common.sh"
source "$SCRIPT_DIR/worktree-detect.sh"

PORT_REGISTRY="${HOME}/.claude/worktree-ports.json"

# --- Parse hook input ---
HOOK_INPUT=$(read_hook_input)
WORKTREE_NAME=$(echo "$HOOK_INPUT" | python3 -c "import sys,json; print(json.load(sys.stdin).get('name',''))" 2>/dev/null || echo "")
WORKTREE_CWD=$(echo "$HOOK_INPUT" | python3 -c "import sys,json; print(json.load(sys.stdin).get('cwd',''))" 2>/dev/null || echo "$(pwd)")

if [ -z "$WORKTREE_NAME" ]; then
  echo "WORKTREE: No worktree name provided, skipping isolation setup" >&2
  exit 0
fi

SLUG=$(worktree_slug "$WORKTREE_NAME")
WORKTREE_PATH="${WORKTREE_CWD}/.claude/worktrees/${WORKTREE_NAME}"

echo "WORKTREE: Setting up isolation for '$SLUG'" >&2

# --- Detect project ---
PROJECT_TYPE=$(detect_project_type "$WORKTREE_CWD")
DB_TYPE=$(detect_database "$WORKTREE_CWD")
ENV_FILE=$(detect_env_file "$WORKTREE_CWD")
PROJECT_NAME=$(detect_project_name "$WORKTREE_CWD")
read -r HAS_DOCKER HAS_DOCKER_COMPOSE COMPOSE_CMD <<< "$(detect_docker)"

echo "WORKTREE: project=$PROJECT_TYPE db=$DB_TYPE docker=$HAS_DOCKER" >&2

# --- Compute ports ---
PORT_BASE=$(compute_port_base "$SLUG" "$WORKTREE_CWD")
APP_PORT=$PORT_BASE
DB_PORT=$((PORT_BASE + 1))
VECTOR_PORT=$((PORT_BASE + 2))
VLOGS_PORT=$((PORT_BASE + 3))
VMETRICS_PORT=$((PORT_BASE + 4))

echo "WORKTREE: port range ${PORT_BASE}-$((PORT_BASE + 9))" >&2

# --- Create .env for worktree ---
if [ -d "$WORKTREE_PATH" ]; then
  WORKTREE_ENV="$WORKTREE_PATH/.env"

  # Start with base .env if it exists
  if [ -n "$ENV_FILE" ] && [ -f "$ENV_FILE" ]; then
    cp "$ENV_FILE" "$WORKTREE_ENV"
  else
    touch "$WORKTREE_ENV"
  fi

  # Append worktree-specific overrides
  cat >> "$WORKTREE_ENV" <<EOF

# --- Worktree isolation (auto-generated by claude-harness) ---
WORKTREE_NAME=${WORKTREE_NAME}
WORKTREE_SLUG=${SLUG}
PORT=${APP_PORT}
DOCKER_COMPOSE_PROJECT_NAME=harness-${SLUG}
EOF

  # Override DATABASE_URL if present
  DB_NAME="${PROJECT_NAME}_wt_${SLUG}"
  DB_NAME=$(echo "$DB_NAME" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9_-]/_/g')

  case "$DB_TYPE" in
    postgresql)
      # Extract connection details from existing DATABASE_URL or use defaults
      if grep -q 'DATABASE_URL' "$WORKTREE_ENV" 2>/dev/null; then
        # Replace the database name in the URL
        sed -i.bak "s|DATABASE_URL=.*|# Original: $(grep DATABASE_URL "$WORKTREE_ENV" | head -1)\nDATABASE_URL=postgresql://localhost:5432/${DB_NAME}|" "$WORKTREE_ENV" 2>/dev/null || true
        rm -f "${WORKTREE_ENV}.bak"
      else
        echo "DATABASE_URL=postgresql://localhost:5432/${DB_NAME}" >> "$WORKTREE_ENV"
      fi
      echo "DATABASE_NAME=${DB_NAME}" >> "$WORKTREE_ENV"
      ;;
    sqlite)
      echo "DATABASE_URL=sqlite:///${WORKTREE_PATH}/db_${SLUG}.sqlite3" >> "$WORKTREE_ENV"
      ;;
    mysql)
      echo "DATABASE_URL=mysql://localhost:3306/${DB_NAME}" >> "$WORKTREE_ENV"
      echo "DATABASE_NAME=${DB_NAME}" >> "$WORKTREE_ENV"
      ;;
  esac

  echo "WORKTREE: created .env at $WORKTREE_ENV" >&2
fi

# --- Create database ---
case "$DB_TYPE" in
  postgresql)
    if command -v createdb >/dev/null 2>&1; then
      createdb "$DB_NAME" 2>/dev/null && echo "WORKTREE: created PostgreSQL database $DB_NAME" >&2 || echo "WORKTREE: PostgreSQL database $DB_NAME already exists or creation failed (continuing)" >&2
    else
      echo "WORKTREE: psql/createdb not available, skipping database creation" >&2
    fi
    ;;
  sqlite)
    # Copy existing SQLite DB if present
    for dbf in "$WORKTREE_CWD"/*.db "$WORKTREE_CWD"/*.sqlite3; do
      if [ -f "$dbf" ] && [ -d "$WORKTREE_PATH" ]; then
        cp "$dbf" "$WORKTREE_PATH/" 2>/dev/null && echo "WORKTREE: copied $(basename "$dbf") to worktree" >&2 || true
      fi
    done
    ;;
  mysql)
    if command -v mysql >/dev/null 2>&1; then
      mysql -e "CREATE DATABASE IF NOT EXISTS \`${DB_NAME}\`" 2>/dev/null && echo "WORKTREE: created MySQL database $DB_NAME" >&2 || echo "WORKTREE: MySQL database creation failed (continuing)" >&2
    else
      echo "WORKTREE: mysql client not available, skipping database creation" >&2
    fi
    ;;
  none)
    echo "WORKTREE: no database detected, skipping" >&2
    ;;
esac

# --- Start docker-compose with project isolation ---
if [ "$HAS_DOCKER_COMPOSE" = "true" ] && [ -d "$WORKTREE_PATH" ]; then
  # Look for compose file in worktree
  COMPOSE_FILE=""
  for cf in "$WORKTREE_PATH/docker-compose.yml" "$WORKTREE_PATH/docker-compose.yaml" "$WORKTREE_PATH/compose.yml" "$WORKTREE_PATH/compose.yaml"; do
    if [ -f "$cf" ]; then
      COMPOSE_FILE="$cf"
      break
    fi
  done

  if [ -n "$COMPOSE_FILE" ]; then
    echo "WORKTREE: starting docker-compose with project name harness-${SLUG}" >&2
    (cd "$WORKTREE_PATH" && $COMPOSE_CMD -p "harness-${SLUG}" up -d 2>&1 | tail -5) >&2 || echo "WORKTREE: docker-compose start failed (continuing)" >&2
  fi
fi

# --- Register in port registry ---
python3 -c "
import json, os, fcntl, time

registry_path = '$PORT_REGISTRY'
slug = '$SLUG'
entry = {
    'project': '$WORKTREE_CWD',
    'worktree_path': '$WORKTREE_PATH',
    'port_base': $PORT_BASE,
    'ports': {
        'app': $APP_PORT,
        'db': $DB_PORT,
        'vector': $VECTOR_PORT,
        'vlogs': $VLOGS_PORT,
        'vmetrics': $VMETRICS_PORT
    },
    'db_name': '${DB_NAME:-}',
    'db_type': '$DB_TYPE',
    'docker_project': 'harness-$SLUG',
    'created_at': time.strftime('%Y-%m-%dT%H:%M:%SZ', time.gmtime())
}

os.makedirs(os.path.dirname(registry_path), exist_ok=True)

# Atomic read-modify-write with file locking
fd = os.open(registry_path, os.O_RDWR | os.O_CREAT)
try:
    fcntl.flock(fd, fcntl.LOCK_EX)
    content = os.read(fd, 1024*1024).decode('utf-8').strip()
    registry = json.loads(content) if content else {}
    registry[slug] = entry
    os.lseek(fd, 0, 0)
    os.ftruncate(fd, 0)
    os.write(fd, json.dumps(registry, indent=2).encode('utf-8'))
finally:
    fcntl.flock(fd, fcntl.LOCK_UN)
    os.close(fd)
" 2>/dev/null && echo "WORKTREE: registered in port registry" >&2 || echo "WORKTREE: port registry update failed (continuing)" >&2

echo "WORKTREE: isolation setup complete" >&2

# CRITICAL: Output worktree path to stdout (required by Claude Code)
echo "$WORKTREE_PATH"
